# The Alexa top list, http://s3.amazonaws.com/alexa-static/top-1m.csv.zip
# alexa_list: "data/alexa-1m-2021-01-04.csv.gz"
alexa_list: "data/alexa-1m-2021-03-01.csv.zip"
# Versions of QUIC supported in our experiments
supported_versions: ["h3-29"]
# Second level domains that whose representation in the dataset are reduced
clamp_sld_domains: ["blogspot.com", "appspot.com", "myshopify.com"]

# The maximum number of URLs to attempt to fetch
max_fetch_urls: 1000

# The number of collection repetitions
collect_reps: 20

# Location of the neqo directory
neqo: "/Users/luca/Documents/ETHZ/Thesis/code/neqo-qcd/"

# Root directory containing "results" folder
rootdir: "/Volumes/Isis/Thesis/qcd-experiments"
# current seed working on for aggregated data
seeddir: "decafbad"
# current config working on for aggregated data
configdir: "config1-tests"
