---
# The Alexa top list, http://s3.amazonaws.com/alexa-static/top-1m.csv.zip
alexa_list: resources/alexa-top10-2021-03-12.csv.gz

# Versions of QUIC supported in our experiments
quic_versions: ["h3-29"]

# Second level domains that whose representation in the dataset are reduced
frequent_slds: ["blogspot.com", "appspot.com", "myshopify.com"]

# The maximum number of URLs to attempt to fetch
max_fetch_urls: 1000

# The log level passed to RUST_LOG for the neqo-client
# neqo_log_level: "neqo_transport=info,neqo_csdef=trace"
neqo_log_level: "neqo=trace"

experiment:
  excess_msd:
    repetitions: 1
    padding: { rate: 1, duration: 10, interval: 5 }  # Mbps, seconds, milliseconds
    excess_values: [ 16, 100, 500, 1000, 1500, 2000]
