# The Alexa top list, http://s3.amazonaws.com/alexa-static/top-1m.csv.zip
alexa_list: "data/alexa-1m-2021-01-04.csv.gz"
# Versions of QUIC supported in our experiments
supported_versions: ["h3-29"]
# Second level domains that whose representation in the dataset are reduced
clamp_sld_domains: ["blogspot.com", "appspot.com"]

# The maximum number of URLs to attempt to fetch
max_fetch_urls: 1000
