---
# The Alexa top list, http://s3.amazonaws.com/alexa-static/top-1m.csv.zip
alexa_list: resources/alexa-top1000-2021-04-08.csv.gz

# Versions of QUIC supported in our experiments
quic_versions: ["h3-29"]

# Second level domains that whose representation in the dataset are reduced
frequent_slds: ["blogspot.com", "appspot.com", "myshopify.com", "withgoogle.com", "translate.goog"]

# The maximum number of URLs to attempt to fetch
max_fetch_urls: 100

# The log level passed to RUST_LOG for the neqo-client
neqo_log_level: "neqo=trace,neqo_transport=trace"

# The User-Agent to use for collections
user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"

experiment:
  scores:
    ts_offset: {min: 0, max: 200, inc: 5}
    resample_rates: ["5ms", "25ms", "50ms"]
  excess_msd:
    padding: { rate: 1, duration: 10, interval: 5 }  # Mbps, seconds, milliseconds
    excess_values: [ 16, 1000, 2000]
  front_single_eval:
    front_config:
      max_client_packets: 2500
      max_server_packets: 2500
      packet_size: 1200
      peak_minimum: 1
      peak_maximum: 14
  tamaraw_single_eval:
    tamaraw_config:
      packet_size: 750
      rate_in: 0.005
      rate_out: 0.02
      pad_multiple: 100
