---
# The Alexa top list, http://s3.amazonaws.com/alexa-static/top-1m.csv.zip
alexa_list: resources/alexa-top1000-2021-04-08.csv.gz

# Versions of QUIC supported in our experiments
quic_versions: ["h3-29"]

# Second level domains that whose representation in the dataset are reduced
frequent_slds: ["blogspot.com", "appspot.com", "myshopify.com", "withgoogle.com", "translate.goog"]

# The maximum number of URLs to attempt to fetch
max_fetch_urls: 100

# The log level passed to RUST_LOG for the neqo-client
neqo_log_level: "neqo=trace,neqo_transport=trace"

experiment:
  excess_msd:
    repetitions: 1
    padding: { rate: 1, duration: 10, interval: 5 }  # Mbps, seconds, milliseconds
    excess_values: [ 16, 1000, 2000]
